import AppKit
import CryptoKit
import Foundation

struct ClipboardRepresentation: Codable {
    let type: String
    let data: Data
}

/// The pasteboard data of a clip. It stays on disk and is only loaded to restore or preview a clip.
struct ClipContent: Codable {
    static let itemBreak = "app.copyclip.item-break"

    var representations: [ClipboardRepresentation]

    var text: String? {
        guard let representation = representations.first(where: { $0.type == NSPasteboard.PasteboardType.string.rawValue }) else { return nil }
        return String(data: representation.data, encoding: .utf8)
            ?? String(data: representation.data, encoding: .utf16)
    }

    var hash: String {
        var hasher = SHA256()
        for representation in representations {
            hasher.update(data: Data("\(representation.type)\u{0}\(representation.data.count)\u{0}".utf8))
            hasher.update(data: representation.data)
        }
        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }
}

/// The lightweight details of a clip, kept in memory for the menu, search, and list.
struct ClipboardItem: Codable, Identifiable {
    static let previewLimit = 2_000
    static let excerptLimit = 501

    let id: UUID
    let copiedAt: Date
    var preview: String
    /// The start of the clip's plain text, or nil when the clip has no text.
    var textExcerpt: String?
    var contentHash: String
    let sourceBundleIdentifier: String?
    let sourceAppName: String?
    var customTitle: String?
    var isPinned: Bool

    init(id: UUID, copiedAt: Date, preview: String, content: ClipContent,
         sourceBundleIdentifier: String? = nil, sourceAppName: String? = nil,
         customTitle: String? = nil, isPinned: Bool = false) {
        self.id = id
        self.copiedAt = copiedAt
        self.preview = String(preview.prefix(Self.previewLimit))
        self.textExcerpt = Self.excerpt(of: content)
        self.contentHash = content.hash
        self.sourceBundleIdentifier = sourceBundleIdentifier
        self.sourceAppName = sourceAppName
        self.customTitle = customTitle
        self.isPinned = isPinned
    }

    static func excerpt(of content: ClipContent) -> String? {
        content.text.map { String($0.trimmingCharacters(in: .whitespacesAndNewlines).prefix(excerptLimit)) }
    }

    var hasText: Bool { textExcerpt != nil }

    var displayTitle: String {
        guard let customTitle, !customTitle.isEmpty else { return preview }
        return customTitle
    }

    var sourceDisplayName: String { sourceAppName ?? sourceBundleIdentifier ?? "Unknown app" }
}

/// The format used before clip data was stored apart from clip details.
private struct LegacyClipboardItem: Decodable {
    let id: UUID
    let copiedAt: Date
    let preview: String
    let representations: [ClipboardRepresentation]
    let sourceBundleIdentifier: String?
    let sourceAppName: String?
    let customTitle: String?
    let isPinned: Bool?

    var content: ClipContent { ClipContent(representations: representations) }

    var item: ClipboardItem {
        ClipboardItem(id: id, copiedAt: copiedAt, preview: preview, content: content,
                      sourceBundleIdentifier: sourceBundleIdentifier, sourceAppName: sourceAppName,
                      customTitle: customTitle, isPinned: isPinned ?? false)
    }
}

final class ClipboardStore {
    /// Larger pasteboard representations are not saved.
    static let maxRepresentationBytes = 32 * 1024 * 1024

    private static let privateTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]
    /// File promises can't be fulfilled once the source app has moved on, so they aren't saved.
    private static let skippedTypes: Set<String> = [
        "com.apple.NSFilePromiseItemMetaData",
        "com.apple.pasteboard.promised-file-content-type",
        "com.apple.pasteboard.promised-file-url",
        "com.apple.pasteboard.promised-suggested-file-name"
    ]
    private static let tiffTypes: Set<String> = [
        NSPasteboard.PasteboardType.tiff.rawValue,
        "NeXT TIFF v4.0 pasteboard type"
    ]

    private(set) var items: [ClipboardItem] = []
    var onChange: (() -> Void)?
    private let legacyURL: URL
    private let indexURL: URL
    private let entriesDirectory: URL
    private let saveQueue = DispatchQueue(label: "app.copyclip.persistence", qos: .utility)

    init(fileURL: URL? = nil) {
        let defaultDirectory = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Copyclip", isDirectory: true)
        let directory = fileURL?.deletingLastPathComponent() ?? defaultDirectory
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        legacyURL = fileURL ?? directory.appendingPathComponent("History.plist")
        indexURL = directory.appendingPathComponent("HistoryIndex.plist")
        entriesDirectory = directory.appendingPathComponent("Clips", isDirectory: true)
        try? FileManager.default.createDirectory(at: entriesDirectory, withIntermediateDirectories: true)

        if let data = try? Data(contentsOf: indexURL),
           let ids = try? PropertyListDecoder().decode([UUID].self, from: data) {
            items = ids.compactMap(loadItem)
        } else if let data = try? Data(contentsOf: legacyURL),
                  let loaded = try? PropertyListDecoder().decode([LegacyClipboardItem].self, from: data) {
            migrateLegacyHistory(loaded)
        }
    }

    var pinnedItems: [ClipboardItem] { items.filter(\.isPinned) }

    func capture(from pasteboard: NSPasteboard, sourceBundleIdentifier: String? = nil,
                 sourceAppName: String? = nil, maxItems: Int = 0) -> Bool {
        guard let pasteboardItems = pasteboard.pasteboardItems, !pasteboardItems.isEmpty else { return false }
        if pasteboardItems.contains(where: { item in item.types.contains(where: { Self.privateTypes.contains($0.rawValue) }) }) {
            return false
        }

        var representations: [ClipboardRepresentation] = []
        for item in pasteboardItems {
            for type in Self.typesToCapture(item.types) {
                guard let data = item.data(forType: type), data.count <= Self.maxRepresentationBytes else { continue }
                representations.append(ClipboardRepresentation(type: type.rawValue, data: data))
            }
            representations.append(ClipboardRepresentation(type: ClipContent.itemBreak, data: Data()))
        }
        guard representations.count > pasteboardItems.count else { return false }

        let content = ClipContent(representations: representations)
        let newItem = ClipboardItem(id: UUID(), copiedAt: Date(), preview: Self.preview(for: pasteboard),
                                    content: content, sourceBundleIdentifier: sourceBundleIdentifier,
                                    sourceAppName: sourceAppName)
        if items.first?.contentHash == newItem.contentHash { return false }
        items.insert(newItem, at: 0)
        let removed = trimToLimit(maxItems)
        persist(item: newItem, content: content, removedIDs: removed, updateIndex: true)
        onChange?()
        return true
    }

    /// Reads a clip's pasteboard data from disk.
    func content(for item: ClipboardItem) -> ClipContent? {
        let url = contentURL(for: item.id)
        // Wait for pending writes so a clip saved moments ago can be read back.
        return saveQueue.sync {
            autoreleasepool {
                guard let data = try? Data(contentsOf: url) else { return nil }
                return try? PropertyListDecoder().decode(ClipContent.self, from: data)
            }
        }
    }

    @discardableResult
    func restore(_ item: ClipboardItem, to pasteboard: NSPasteboard) -> Bool {
        guard let content = content(for: item) else { return false }
        var result: [NSPasteboardItem] = []
        var current = NSPasteboardItem()
        for representation in content.representations {
            if representation.type == ClipContent.itemBreak {
                if !current.types.isEmpty { result.append(current) }
                current = NSPasteboardItem()
            } else {
                current.setData(representation.data, forType: NSPasteboard.PasteboardType(representation.type))
            }
        }
        if !current.types.isEmpty { result.append(current) }
        guard !result.isEmpty else { return false }
        pasteboard.clearContents()
        pasteboard.writeObjects(result)
        return true
    }

    func setPinned(id: UUID, to pinned: Bool) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        items[index].isPinned = pinned
        persist(item: items[index])
        onChange?()
    }

    func rename(id: UUID, to title: String) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        let cleaned = title.trimmingCharacters(in: .whitespacesAndNewlines)
        items[index].customTitle = cleaned.isEmpty ? nil : cleaned
        persist(item: items[index])
        onChange?()
    }

    func editText(id: UUID, to text: String) {
        guard let index = items.firstIndex(where: { $0.id == id }), items[index].hasText else { return }
        let pasteboardItem = NSPasteboardItem()
        pasteboardItem.setString(text, forType: .string)
        guard let data = pasteboardItem.data(forType: .string) else { return }
        let content = ClipContent(representations: [
            ClipboardRepresentation(type: NSPasteboard.PasteboardType.string.rawValue, data: data),
            ClipboardRepresentation(type: ClipContent.itemBreak, data: Data())
        ])
        items[index].preview = Self.cleanPreview(text)
        items[index].textExcerpt = ClipboardItem.excerpt(of: content)
        items[index].contentHash = content.hash
        persist(item: items[index], content: content)
        onChange?()
    }

    func delete(id: UUID) {
        guard items.contains(where: { $0.id == id }) else { return }
        items.removeAll { $0.id == id }
        persist(removedIDs: [id], updateIndex: true)
        onChange?()
    }

    func deleteAll() {
        let removed = items.map(\.id)
        items.removeAll()
        persist(removedIDs: removed, updateIndex: true)
        onChange?()
    }

    func enforceLimit(_ limit: Int) {
        let removed = trimToLimit(limit)
        guard !removed.isEmpty else { return }
        persist(removedIDs: removed, updateIndex: true)
        onChange?()
    }

    func flush() { saveQueue.sync { } }

    /// Skips types that can't be restored later and TIFF copies of images that also come as PNG.
    static func typesToCapture(_ types: [NSPasteboard.PasteboardType]) -> [NSPasteboard.PasteboardType] {
        let hasPNG = types.contains(.png)
        return types.filter { type in
            let name = type.rawValue
            if skippedTypes.contains(name) || name.hasPrefix("CorePasteboardFlavorType") { return false }
            return !(hasPNG && tiffTypes.contains(name))
        }
    }

    private func trimToLimit(_ limit: Int) -> [UUID] {
        guard limit > 0 else { return [] }
        var removed: [UUID] = []
        while items.count > limit, let index = items.lastIndex(where: { !$0.isPinned }) {
            removed.append(items.remove(at: index).id)
        }
        return removed
    }

    private func contentURL(for id: UUID) -> URL {
        entriesDirectory.appendingPathComponent(id.uuidString).appendingPathExtension("plist")
    }

    private func metadataURL(for id: UUID) -> URL {
        entriesDirectory.appendingPathComponent(id.uuidString + ".meta").appendingPathExtension("plist")
    }

    private func loadItem(id: UUID) -> ClipboardItem? {
        autoreleasepool {
            if let data = try? Data(contentsOf: metadataURL(for: id)),
               let item = try? PropertyListDecoder().decode(ClipboardItem.self, from: data) {
                return item
            }
            // Older clip files hold the details and data together; save the details on their own once.
            guard let data = try? Data(contentsOf: contentURL(for: id)),
                  let legacy = try? PropertyListDecoder().decode(LegacyClipboardItem.self, from: data) else { return nil }
            let item = legacy.item
            try? Self.encoded(item).write(to: metadataURL(for: id), options: .atomic)
            return item
        }
    }

    private func persist(item: ClipboardItem? = nil, content: ClipContent? = nil,
                         removedIDs: [UUID] = [], updateIndex: Bool = false) {
        let ids = updateIndex ? items.map(\.id) : []
        let index = indexURL
        let contentURL = item.map { self.contentURL(for: $0.id) }
        let metadataURL = item.map { self.metadataURL(for: $0.id) }
        let removedURLs = removedIDs.flatMap { [self.contentURL(for: $0), self.metadataURL(for: $0)] }
        saveQueue.async {
            do {
                if let content, let contentURL { try Self.encoded(content).write(to: contentURL, options: .atomic) }
                if let item, let metadataURL { try Self.encoded(item).write(to: metadataURL, options: .atomic) }
                if updateIndex { try Self.encoded(ids).write(to: index, options: .atomic) }
                for url in removedURLs { try? FileManager.default.removeItem(at: url) }
            } catch {
                // Keep the previous on-disk index and clip files if a write fails.
            }
        }
    }

    private func migrateLegacyHistory(_ loaded: [LegacyClipboardItem]) {
        items = loaded.map(\.item)
        do {
            for (legacy, item) in zip(loaded, items) {
                try Self.encoded(legacy.content).write(to: contentURL(for: item.id), options: .atomic)
                try Self.encoded(item).write(to: metadataURL(for: item.id), options: .atomic)
            }
            try Self.encoded(items.map(\.id)).write(to: indexURL, options: .atomic)
            try? FileManager.default.removeItem(at: legacyURL)
        } catch {
            // Keep the old single-file history as the recovery copy if migration fails.
        }
    }

    private static func encoded<T: Encodable>(_ value: T) throws -> Data {
        let encoder = PropertyListEncoder()
        encoder.outputFormat = .binary
        return try encoder.encode(value)
    }

    private static func preview(for pasteboard: NSPasteboard) -> String {
        if let text = pasteboard.string(forType: .string) { return cleanPreview(text) }
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
           let first = urls.first {
            return urls.count == 1 ? first.lastPathComponent : "\(urls.count) files"
        }
        if pasteboard.canReadItem(withDataConformingToTypes: ["public.image"]) { return "Image" }
        if pasteboard.canReadItem(withDataConformingToTypes: ["public.rtf"]) { return "Formatted text" }
        return "Clipboard item"
    }

    private static func cleanPreview(_ text: String) -> String {
        let cleaned = String(text.prefix(ClipboardItem.previewLimit * 2))
            .replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return cleaned.isEmpty ? "Empty text" : String(cleaned.prefix(ClipboardItem.previewLimit))
    }
}
