import AppKit
import Foundation

struct ClipboardRepresentation: Codable {
    let type: String
    let data: Data
}

struct ClipboardItem: Codable, Identifiable {
    let id: UUID
    let copiedAt: Date
    let preview: String
    let representations: [ClipboardRepresentation]

    var signature: Int {
        var hasher = Hasher()
        for representation in representations {
            hasher.combine(representation.type)
            hasher.combine(representation.data)
        }
        return hasher.finalize()
    }
}

final class ClipboardStore {
    private(set) var items: [ClipboardItem] = []
    private let fileURL: URL
    private let saveQueue = DispatchQueue(label: "app.copyclip.persistence")

    init(fileURL: URL? = nil) {
        let defaultDirectory = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Copyclip", isDirectory: true)
        let directory = fileURL?.deletingLastPathComponent() ?? defaultDirectory
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        self.fileURL = fileURL ?? directory.appendingPathComponent("History.plist")
        if let data = try? Data(contentsOf: self.fileURL),
           let loaded = try? PropertyListDecoder().decode([ClipboardItem].self, from: data) {
            items = loaded
        }
    }

    func capture(from pasteboard: NSPasteboard) -> Bool {
        guard let pasteboardItems = pasteboard.pasteboardItems, !pasteboardItems.isEmpty else { return false }

        let privateTypes: Set<String> = [
            "org.nspasteboard.TransientType",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType"
        ]
        if pasteboardItems.contains(where: { item in item.types.contains(where: { privateTypes.contains($0.rawValue) }) }) {
            return false
        }

        var representations: [ClipboardRepresentation] = []
        for item in pasteboardItems {
            for type in item.types {
                if let data = item.data(forType: type) {
                    representations.append(ClipboardRepresentation(type: type.rawValue, data: data))
                }
            }
            // Preserve the boundaries between multiple pasteboard items.
            representations.append(ClipboardRepresentation(type: "app.copyclip.item-break", data: Data()))
        }
        guard representations.count > pasteboardItems.count else { return false }

        let newItem = ClipboardItem(
            id: UUID(), copiedAt: Date(),
            preview: Self.preview(for: pasteboard),
            representations: representations
        )
        if items.first?.signature == newItem.signature { return false }
        items.insert(newItem, at: 0)
        save()
        return true
    }

    func restore(_ item: ClipboardItem, to pasteboard: NSPasteboard) {
        var result: [NSPasteboardItem] = []
        var current = NSPasteboardItem()
        for representation in item.representations {
            if representation.type == "app.copyclip.item-break" {
                if !current.types.isEmpty { result.append(current) }
                current = NSPasteboardItem()
            } else {
                current.setData(representation.data, forType: NSPasteboard.PasteboardType(representation.type))
            }
        }
        if !current.types.isEmpty { result.append(current) }
        guard !result.isEmpty else { return }
        pasteboard.clearContents()
        pasteboard.writeObjects(result)
    }

    func deleteAll() {
        items.removeAll()
        save()
    }

    func flush() {
        saveQueue.sync { }
    }

    private func save() {
        let snapshot = items
        let destination = fileURL
        saveQueue.async {
            guard let data = try? PropertyListEncoder().encode(snapshot) else { return }
            try? data.write(to: destination, options: .atomic)
        }
    }

    private static func preview(for pasteboard: NSPasteboard) -> String {
        if let text = pasteboard.string(forType: .string) {
            let cleaned = text.replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
                .trimmingCharacters(in: .whitespacesAndNewlines)
            if !cleaned.isEmpty { return cleaned }
        }
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
           let first = urls.first {
            return urls.count == 1 ? first.lastPathComponent : "\(urls.count) files"
        }
        if pasteboard.canReadItem(withDataConformingToTypes: ["public.image"]) { return "Image" }
        if pasteboard.canReadItem(withDataConformingToTypes: ["public.rtf"]) { return "Formatted text" }
        return "Clipboard item"
    }
}
